### ISSUE TITLE
Warning in Admin Backend: "Changes you made may not be saved." (Evolution CMS)

### ISSUE THREAD

**Issue by q2apro** [evolution-cms/evolution#1058]
I cannot find the reason for the bug, but on each link I click in the admin backend, EvoCMS is warning me with:

> Leave site?
> Changes you made may not be saved.

I click on "Leave", then I get: 

> Server isn't available. Check your internet connection!

Happens in **Google Chrome** v73.0.3683.103, but not in Microsoft Edge.

Can anyone tell me what this is causing? Which Javascript (?) file do I have to examine?

I have not changed any file. Just updated Windows 10, but I cannot believe that this is related to the Windows update...

**Comment by 64j** [comment]
Yes, this is a new bug in the latest versions of Chrome

**Comment by 64j** [comment]
@q2apro 

Comment out the function call in the file
https://github.com/evolution-cms/evolution/blob/1.4.x/manager/media/script/main.js#L430-L445

```checkDirt(e);```


And add to the file
https://github.com/evolution-cms/evolution/blob/1.4.x/manager/includes/footer.inc.php

```html
<script>
  if (actions && typeof actions.save === 'function') {
    (function(a) {
      window.actions.save = function() {
        if (!checkDirt()) {
          a();
        }
      };
    })(actions.save);
  }
</script>
```


Check, please

**Comment by q2apro** [comment]
Commenting out `checkDirt(e);` removed the warnings.

However, when editing a document and navigating away without saving, now there is no warning anymore. The JS code for the footer should trigger the warning?

**Comment by q2apro** [comment]
With this fix to save a document is not possible anymore!

Chrome Console says:

>VM176 main.js:272 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by safonovpro** [comment]
My temporary solution. In manager\media\script\main.js:
Lines 270 - 279:
`evo.checkConnectionToServer = function() {
  return new Promise((resolve, reject) => {
    var xhr = new XMLHttpRequest();

    try {
      xhr.open('HEAD', evo.urlCheckConnectionToServer + '?time=' + new Date().getTime(), true);
      xhr.send();
      xhr.onreadystatechange = () => {
        if (xhr.readyState === 2) {
          resolve(xhr.status >= 200 && xhr.status < 300 || xhr.status === 304);
        }
      }
    } catch(error) {
      reject(error);
    }
  });
};`
Lines 398 - 401:
`async function checkDirt(evt) {
  evt = evt || window.event;
  var message = '';
  const checkConnectionToServerResult = await evo.checkConnectionToServer();

  if (!checkConnectionToServerResult) {`

**Comment by 64j** [comment]
@q2apro 
The script in footer.php will make a server availability check when saving a document

**Comment by Sybrenb** [comment]
I have the same problem, will this be fixed in an upcoming update?

**Comment by safonovpro** [comment]
Temporarily, you can do this:
Line 270 in manager\media\script\main.js
<pre>
evo.checkConnectionToServer = function() {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();

    xhr.addEventListener('load', () => resolve(xhr.status >= 200 && xhr.status < 300 || xhr.status === 304));
    xhr.addEventListener('error', () => resolve(false));
    xhr.addEventListener('timeout', () => resolve(false));

    xhr.open('HEAD', evo.urlCheckConnectionToServer + '?time=' + new Date().getTime(), true);
    xhr.send();
  });
};
</pre>

Line 398 manager\media\script\main.js
<pre>
async function checkDirt(evt) {
  evt = evt || window.event;
  var message = '';
  const checkConnectionToServerResult = await evo.checkConnectionToServer();

  if (!checkConnectionToServerResult) {
</pre>

**Comment by dmi3yy** [comment]
Fast solution: 
Line 270 in manager\media\script\main.js

this: 
```
evo.checkConnectionToServer = function() {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();

    xhr.addEventListener('load', () => resolve(xhr.status >= 200 && xhr.status < 300 || xhr.status === 304));
    xhr.addEventListener('error', () => resolve(false));
    xhr.addEventListener('timeout', () => resolve(false));

    xhr.open('GET', evo.urlCheckConnectionToServer + '?time=' + new Date().getTime(), true);
    xhr.send();
  });
};
```
change to 
```
evo.checkConnectionToServer = function() {
  return true;
};
```


soon will fix and released 1.4.9

**Comment by 64j** [comment]
@dmi3yy 
Or plugin  **OnManagerMainFrameHeaderHTMLBlock** ))

```php
$e = $modx->event;
if ($e->name == 'OnManagerMainFrameHeaderHTMLBlock') {
	$e->addOutput('<script>document.addEventListener(\'DOMContentLoaded\', function() {window.checkDirt = function() {return true}});</script>');
}
```

**Comment by user83743** [comment]
the above code:

evo.checkConnectionToServer = function() {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();

    xhr.addEventListener('load', () => resolve(xhr.status >= 200 && xhr.status < 300 || xhr.status === 304));
    xhr.addEventListener('error', () => resolve(false));
    xhr.addEventListener('timeout', () => resolve(false));

    xhr.open('GET', evo.urlCheckConnectionToServer + '?time=' + new Date().getTime(), true);
    xhr.send();
  });
};

is not in place on evo 1.4.7  manager\media\script\main.js .... is there a quick fix for evo 1.4.7?

**Comment by safonovpro** [comment]
> is not in place on evo 1.4.7 manager\media\script\main.js .... is there a quick fix for evo 1.4.7?

I don't know about 1.4.7. In 1.4.6 the file is and the problem is gone.

**Comment by user83743** [comment]
thanks for the update

**Comment by ricardo-lewis** [comment]
I have a copy of Evo 1.4.6, and stable Chrome 73.0.3683.103 (Mac) from April 4th. 

The problem seems to have disappeared without updating either Evo or Chrome, so I have no idea what's going on.

**Comment by user83743** [comment]
wow! yes, i see that too. i have up to date chrome Version 73.0.3683.103 (Official Build) (32-bit) - and i logged into 2 EVO sites that i tested last week and the bug is gone now, and we did nothing as we were waiting to see if any new fix appeared here on github. very odd. thanks for the update @ricardo-lewis

**Comment by modwebpl** [comment]
topic still "open" ? o.0

**Comment by Dmi3yy** [comment]
Fixed

**Comment by BBloke** [comment]
This has shown up again.  Chrome 80.0.3987.132 as well as Firefox and Edge.

**Comment by djad33** [comment]
I can confirm this is happening again. Evo 2.0.1 on Chrome 80.0.3987.132 (Official Build) (64-bit) [macOS].

Is not happening for me on Firefox 73.0.1 (64-bit) or 74.0 (64-bit) [macOS]

**Comment by ricardo-lewis** [comment]
I was able to fix the issue recently by updating to 1.4.10 and then deleting out all cookies / cache.

**Comment by djad33** [comment]
I'm on 2.0.1. I have cleared cookies and cache. Still occurring, but thanks.

**Comment by fourroses666** [comment]
> Fixed

Doesn't looks to be fixed for 1.4.x

**Comment by Dmi3yy** [comment]
Clear browser cache
