### ISSUE TITLE
Internal Server Error after update to 1.4.1

### ISSUE THREAD

**Issue by leonie12** [evolution-cms/evolution#558]
PHP 7.0
One of my websites has an error 500 in frontend after running update from 1.4.0 to 1.4.1. On live server :-( and  local.
Deactivating phx plugin brings some pages back (of course without phx function) without error 500. Other pages still have error 500 also with phx deactivated.

In manager everything is working.
Other websites working fine after update.

**Comment by modxuser** [comment]
I also had problems with one install, what provider are you with ?

I got it resolved in the end by re-installing completely (took 4 attempts) from scratch, took me all day to get it running - but my problem I think is server related, as I don't use PHX

**Comment by leonie12** [comment]
I do not think that my issue is server related because it happens on live site and local. Installing backup with 1.4.0 solves the issue, updating triggers it.
PHX can not be the only reason because the issue persists on startpage also when phx is deactivated.

**Comment by leonie12** [comment]
It seems that the issue is triggered by some DocLister calls:

`[[DocLister? &parents=`149` &addWhereList=`published=1 AND isfolder=0` &depth=`2` &tpl=`ditto-tpl-related-content` &orderBy=`pub_date DESC` &display=`50` &tvList=`summary-image, summary-image-alt-text, summary-image-title` &extenders=`summary` [*ditto-ids-related-content*] ]]`

and

`[[DocLister? &parents=`149` &documents=`161` &idType=`parents, documents` &depth=`2` &addWhereList=`published=1 AND isfolder=0` &tpl=`ditto-tpl-news-startseite` &orderBy=`pub_date DESC` &display=`6` &tvList=`summary-image-news-startseite, summary-image-alt-text, summary-image-title` &extenders=`splitintrotext`]]`

Removing them solves the issue.

Before update everything was working fine.

**Comment by Pathologic** [comment]
@leonie12 show the error.log.

**Comment by leonie12** [comment]
@Pathologic: Where can I find error.log? System events log is empty.

**Comment by Pathologic** [comment]
Ask your hosting provider. The reason of 500 error is there.

**Comment by leonie12** [comment]
@Pathologic: When it worked before update and works with Ditto instead of DocLister and does not work anymore with DocLister after update I can not see how this should be originated by my hosting provider.

**Comment by Pathologic** [comment]
If you cannot provide error description from error.log, then how this error can be fixed?

**Comment by Pathologic** [comment]
https://github.com/AgelxNash/DocLister/commit/85b46d75118bdb72709fa63d8694bce53e057c60
