### ISSUE TITLE
TinyMCE introtext mode not work

### ISSUE THREAD

**Issue by sazanof** [evolution-cms/evolution#577]
The tinymce editor does not work in the introtext field if you enable this option.
__________________________________________________________________________________________________________
Не работает редактор Tinymce в поле introtext, если включить соответствующую опцию.
```
tinymce.min.js:5 GET https://tarotclub.ru/assets/plugins/tinymce4/tinymce/themes/introtext/theme.min.js net::ERR_ABORTED
```

**Comment by Deesen** [comment]
I guess in Evo-configuration you have set "skin-theme" to "inlite"? If you switch to "modern", does introtext work again?

If yes I will change `$this->set` to `$this->force` at https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/tinymce4/bridge.tinymce4.inc.php#L347 , which should solve this issue generally.

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/37652751-a43214c0-2c4d-11e8-826f-324f574e95d2.png)

**Comment by sazanof** [comment]
> I guess in Evo-configuration you have set "skin-theme" to "inlite"? If you switch to "modern", does introtext work again?
No, it does not work

**Comment by Deesen** [comment]
Changing `$this->set` to `$this->force` also does not work?

**Comment by Deesen** [comment]
@64j Does it help adding `'skinthemeDirectory'=>''` to default-array in https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/tinymce4/gsettings/gsettings.rows.inc.php#L3

**Comment by sazanof** [comment]
> Changing
 $this->set to $this->force also does not work?


@Deesen , yeah, also does not work

**Comment by 64j** [comment]
@Deesen 
need replace
https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/tinymce4/gsettings/gsettings.rows.inc.php#L3

```php
$params = !empty($params) ? $params : array('base_url' => '', 'skinsDirectory' => '', 'skinthemeDirectory' => '');

**Comment by Deesen** [comment]
I could recreate your issue and these 2 solutions fixed it for me on my localhost. Don´t know what is the reason why it doesn´t work for you.

Maybe you can try to remove `'theme'` from the end of this list, does this work? https://github.com/evolution-cms/evolution/blob/develop/assets/plugins/tinymce4/bridge.tinymce4.inc.php#L23

**Comment by 64j** [comment]
@Deesen 
I have an error when I turn on errors on a maximum (PHP 7.2)

**Comment by Deesen** [comment]
@64j Solved now?

**Comment by sazanof** [comment]
I checked on the new site and on the old one, updated to 1.4.1
Upload the archive whis editor , and recreate the plugin
When I select Introtext RTE-enabled, then clear the cache and refresh the page, I get an error
404 - /assets/plugins/tinymce4/tinymce/themes/introtext/theme.min.js
And this is understandable, because the folder introtext does not exist, I can rename the inlet and slip: the console silence, but intotextRTE does not work.
____________________________________________________________________

Я проверил на новом сайте и на старом, обновленным до 1.4.1
Перезалил архив и пересоздал плагин
Когда выбираю Introtext RTE - enabled, затем вычищаю кеш и обновляю станицу, то получаю ошибку
404 - http://modx-dev/assets/plugins/tinymce4/tinymce/themes/introtext/theme.min.js
И это понятно, ведь папки introtext не существует, я могу переименовать inlite и подсунуть: в консоли тишина, но intotextRTE так и не работает.

JS generated on page
![image](https://user-images.githubusercontent.com/3595562/37655586-cdfce3da-2c56-11e8-8c85-f189943879de.png)

**Comment by Deesen** [comment]
If you look into source-code you will find `var config_tinymce4_introtext` which holds a `'theme':'introtext'` causing the error. With my fix this part should be removed. I don´t understand why it is not the case for you.

**Comment by sazanof** [comment]
No, not working, sorry. Checked in the new browser, in order not to sin in the cache. I checked all the changes in the files too.

I'll still try.

**Comment by sazanof** [comment]
How I solved the problem: from Extras installed version 4.3.7.1
and from the website tinymce updated js version to 4.7.9: works both introtext and selection of pictures
But this does not solve the current problem
___________________________________________________________
Как я решил проблему: из Extras установил версию 4.3.7.1

и с сайта tinymce обновил js: работает и introtext и выделение картинок
Но это не решает текущую проблему

**Comment by dmi3yy** [comment]
http://take.ms/GArxD.
